---
# Useful paths
data_folder: "/home/{{ ansible_user }}"
app_folder: "{{ data_folder }}/app"
share_folder: "{{ data_folder }}/share"

docker_compose:
  services:
    unifi:
      image: linuxserver/unifi-controller
      container_name: unifi
      network_mode: host
      volumes:
        - "{{ app_folder }}/unifi:/config"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    ddns: &ddns
      container_name: ddns
      image: sjmayotte/route53-dynamic-dns:latest
      networks:
        - apps
      environment: &ddns_environment
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AWS_REGION: us-east-1
        ROUTE53_HOSTED_ZONE_ID: "{{ aws_ddns_hosted_zone }}"
        ROUTE53_TYPE: A
        ROUTE53_TTL: "300"
        UPDATE_FREQUENCY: "60000"
        SEND_EMAIL_SES: "true"
        SES_FROM_ADDRESS: "{{ ansible_email }}"
        SES_TO_ADDRESS: "{{ ansible_email }}"
        ROUTE53_DOMAIN: "{{ inventory_hostname }}"
    ddns-tower:
      <<: *ddns
      container_name: ddns-tower
      environment:
        <<: *ddns_environment
        ROUTE53_DOMAIN: tower.bovbel.com
    ddns-franklin:
      <<: *ddns
      container_name: ddns-franklin
      environment:
        <<: *ddns_environment
        ROUTE53_DOMAIN: franklin.bovbel.com
    ddns-octopi:
      <<: *ddns
      container_name: ddns-octopi
      environment:
        <<: *ddns_environment
        ROUTE53_DOMAIN: octopi.bovbel.com
    ddns-metal:
      <<: *ddns
      container_name: ddns-metal
      environment:
        <<: *ddns_environment
        ROUTE53_DOMAIN: metal.bovbel.com

caddy:
  remotes:
    franklin:
      host: franklin
      domain: bovbel.com
      auth: oauth
      scheme: https
      port: 443
      users: "{{ admin_users }}"

    metal:
      host: metal
      domain: bovbel.com
      auth: oauth
      scheme: https
      port: 443
      users: "{{ admin_users }}"

    octopi:
      host: octopi
      domain: bovbel.com
      auth: basic
      port: 80
