---
share_users:
  - eugene.tkach@gmail.com
  - igorlitvinov@gmail.com
  - rebecca@bovbel.com
  - rustedghost@gmail.com
  - gamask@gmail.com
  - victorvorobiev@gmail.com
  - woodward.adam.m@gmail.com

# Useful paths
data_folder: /mnt/storage
app_folder: "{{ data_folder }}/app"
media_folder: "{{ data_folder }}/media"
backup_folder: "{{ data_folder }}/backup"
download_folder: "{{ media_folder }}/downloads"
share_folder: "{{ media_folder }}"

pia_username: p4418147
pia_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36383736346664363437303738626166643838353336633434386135366561383966366130653432
  3837336163316635386437626434383531666262303538660a626263313439393263653437373335
  66386534363233316338306539386666303037623931316638346563313331376366613664643065
  6638343761396139370a623834653464666665326162333936306535646333666261343736346464
  6262

zfs_pool: storage

docker_compose:
  services:
    ddns:
      container_name: ddns
      image: sjmayotte/route53-dynamic-dns:latest
      networks:
        - apps
      environment:
        - "AWS_ACCESS_KEY_ID={{ aws_access_key_id }}"
        - "AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }}"
        - "AWS_REGION=us-east-1"
        - "ROUTE53_HOSTED_ZONE_ID={{ aws_ddns_hosted_zone }}"
        - "ROUTE53_DOMAIN={{ inventory_hostname }}"
        - "ROUTE53_TYPE=A"
        - "ROUTE53_TTL=300"
        - "UPDATE_FREQUENCY=60000"
        - "SEND_EMAIL_SES=true"
        - "SES_FROM_ADDRESS={{ ansible_email }}"
        - "SES_TO_ADDRESS={{ ansible_email }}"
    plex:
      image: plexinc/pms-docker:plexpass
      container_name: plex
      networks:
        - apps
      ports:
        - 32400:32400
      volumes:
        - "{{ app_folder }}/plex:/config"
        - "{{ media_folder }}:/mnt/storage/share:ro"
      environment:
        - "PLEX_UID={{ uid }}"
        - "PLEX_GID={{ gid }}"
        - "TZ=America/Toronto"
        - ADVERTISE_IP=http://{{ ansible_default_ipv4.address }}:32400/
      restart: unless-stopped
    tautulli:
      image: linuxserver/tautulli
      container_name: tautulli
      networks:
        - apps
      depends_on:
        - plex
      volumes:
        - "{{ app_folder }}/tautulli:/config"
        - "{{ app_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - "{{ app_folder }}/sonarr:/config"
        - "{{ backup_folder }}/apps/sonarr:/config/Backups"
        - "{{ media_folder }}/tv:/tv"
        - "{{ download_folder }}:/downloads"
        - "/etc/localtime:/etc/localtime:ro"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      networks:
        - apps
      depends_on:
        - jackett
      volumes:
        - "{{ app_folder }}/radarr:/config"
        - "{{ backup_folder }}/apps/radarr:/config/Backups"
        - "{{ media_folder }}/movies:/movies"
        - "{{ download_folder }}:/downloads"
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      networks:
        - apps
      volumes:
        - "{{ app_folder }}/jackett:/config"
      restart: unless-stopped
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
    transmission:
      container_name: transmission
      image: haugene/transmission-openvpn:latest
      cap_add:
        - NET_ADMIN
      networks:
        - apps
      dns:
        - 8.8.8.8
        - 1.1.1.1
      restart: unless-stopped
      volumes:
        - "{{ app_folder }}/transmission/config:/config"
        - "{{ app_folder }}/transmission/home:/data/transmission-home"
        - "{{ download_folder }}:/downloads"
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
        - "WEBPROXY_ENABLED=false"
        - "LOCAL_NETWORK=172.25.0.0/16"
        - "OPENVPN_PROVIDER=PIA"
        - "OPENVPN_CONFIG=CA\ Toronto"
        - "OPENVPN_USERNAME={{ pia_username }}"
        - "OPENVPN_PASSWORD={{ pia_password }}"
        - "CREATE_TUN_DEVICE=true"
        - "TRANSMISSION_INCOMPLETE_DIR_ENABLED=false"
        - "TRANSMISSION_WATCH_DIR=/downloads/watch"
        - "TRANSMISSION_DOWNLOAD_DIR=/downloads"
        - "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true"
        - "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/config/unpack.sh"
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      networks:
        - apps
      environment:
        - "PUID={{ uid }}"
        - "PGID={{ gid }}"
        - "TZ=America/Toronto"
      volumes:
        - "{{ app_folder }}/ombi:/config"
      restart: unless-stopped

caddy:
  endpoints:
    radarr:
      type: proxy
      auth: oauth
      path: /radarr
      host: radarr
      port: 7878
      users: "{{ admin_users }}"

    sonarr:
      type: proxy
      auth: oauth
      path: /sonarr
      host: sonarr
      port: 8989
      users: "{{ admin_users }}"

    tautulli:
      type: proxy
      auth: oauth
      path: /tautulli
      host: tautulli
      port: 8181
      users: "{{ admin_users }}"

    jackett:
      type: proxy
      auth: oauth
      path: /jackett
      host: jackett
      port: 9117
      users: "{{ admin_users }}"

    ombi:
      type: proxy
      auth: null
      path: /ombi
      host: ombi
      port: 3579
      users: "{{ admin_users + share_users }}"

    transmittion:
      type: proxy
      auth: basic
      path: /transmission
      host: transmission
      port: 9091

    share:
      type: share
      auth: oauth
      path: /share
      users: "{{ admin_users + share_users }}"
