media_gid: 8675309

docker_compose:
    services:
        plex:
            image: plexinc/pms-docker:plexpass
            container_name: plex
            networks:
                - apps
            ports:
                - 32400:32400
            volumes:
                - "{{ app_folder }}/plex:/config"
                - "{{ movies_folder }}:/media/Movies"
                - "{{ tv_folder }}:/media/TV"
                - "{{ music_folder }}:/media/Music"
            tmpfs:
                    - "/transcode:uid={{ uid }},gid={{ media_gid }}"
            environment:
                - "PLEX_UID={{ uid }}"
                - "PLEX_GID={{ media_gid }}"
                - "TZ=America/Toronto"
            devices:
                - /dev/dri:/dev/dri
            entrypoint: /bin/sh -c "if [ -d /dev/dri ]; then chmod 755 /dev/dri && chmod 666 /dev/dri/*; fi; /init"
            restart: "unless-stopped"
        tautulli:
            image: linuxserver/tautulli
            container_name: tautulli
            networks:
                - apps
            depends_on:
                - plex
            volumes:
                - "{{ app_folder }}/tautulli:/config"
                - "{{ app_folder }}/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro"
            restart: "unless-stopped"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
        sonarr:
            image: linuxserver/sonarr
            container_name: sonarr
            networks:
                - apps
            depends_on:
                - jackett
            volumes:
                - "/etc/localtime:/etc/localtime:ro"
                - "{{ app_folder }}/sonarr:/config"
                - "{{ tv_folder }}:/tv"
                - "{{ download_folder }}:/downloads"
            restart: "unless-stopped"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
        radarr:
            image: linuxserver/radarr
            container_name: radarr
            networks:
                - apps
            depends_on:
                - jackett
            volumes:
                - /etc/localtime:/etc/localtime:ro
                - "{{ app_folder }}/radarr:/config"
                - "{{ movies_folder }}:/movies"
                - "{{ download_folder }}:/downloads"
            restart: "unless-stopped"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
        jackett:
            image: linuxserver/jackett
            container_name: jackett
            networks:
                - apps
            volumes:
                - "{{ app_folder }}/jackett:/config"
            restart: "unless-stopped"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
        nzbget:
            image: linuxserver/nzbget
            container_name: nzbget
            ports:
                - 6789:6789
            volumes:
                - "{{ app_folder }}/nzbget:/config"
                - "{{ download_folder }}:/downloads"
                - "{{ app_folder }}/nzbget/logs:/logs"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
            restart: "unless-stopped" 
        transmission:
            image: haugene/transmission-openvpn
            container_name: transmission
            cap_add:
                - NET_ADMIN
            networks:
                - apps
            ports:
                - 51413:51413
            restart: "unless-stopped"
            volumes:
                - "{{ app_folder }}/transmission/config:/config"
                - "{{ app_folder }}/transmission/data:/data"
                - "{{ download_folder }}:/downloads"
            environment:
                - "PUID={{ uid }}"
                - "PGID={{ media_gid }}"
                - "TZ=America/Toronto"
                - "WEBPROXY_ENABLED=false"
                - "LOCAL_NETWORK=10.0.0.0/24"
                - "OPENVPN_PROVIDER=NORDVPN"
                  #- "OPENVPN_CONFIG=CA\ Toronto"
                - "OPENVPN_USERNAME={{ nordvpn_username }}"
                - "OPENVPN_PASSWORD={{ nordvpn_password }}"
                - "CREATE_TUN_DEVICE=true"
                - "TRANSMISSION_WATCH_DIR=/downloads/watch"
                - "TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true"
                - "TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=/config/unpack.sh"

caddy:
    remotes:
        plex:
            host: plex
            domain: rjf.ca
            scheme: http
            port: 32400

        nzbget:
            host: nzbget
            domain: rjf.ca
            scheme: http
            port: 6789
            auth: oauth
            roles: ['admin']

    endpoints:
        radarr:
            type: proxy
            auth: oauth
            path: /radarr
            host: radarr
            port: 7878
            roles: ['admin']

        sonarr:
            type: proxy
            auth: oauth
            path: /sonarr
            host: sonarr
            port: 8989
            roles: ['admin']

        tautulli:
            type: proxy
            auth: oauth
            path: /tautulli
            host: tautulli
            port: 8181
            roles: ['admin']

        jackett:
            type: proxy
            auth: oauth
            path: /jackett
            host: jackett
            port: 9117
            roles: ['admin']

        nzbget:
            type: proxy
            auth: oauth
            path: /nzbget
            host: nzbget
            port: 6789
            roles: ['admin']

        transmission:
            type: proxy
            auth: oauth
            path: /transmission
            host: transmission
            port: 9091
            roles: ['admin']
