---
- name: install nfs client
  apt:
    pkg: nfs-common
    state: latest
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: nfs_mounts is defined

- name: Ensure directory exists
  file:
    path: "{{ item.mount }}"
    state: directory
  become: true
  with_items:
    - "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: configure nfs mounts
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.url }}"
    fstype: nfs
    opts: "{{ network_mount_options | join(',') }}"
    state: mounted
  become: true
  with_items:
    - "{{ nfs_mounts }}"
  when: nfs_mounts is defined
