---
- name: make sure media group exists
  group:
    name: "media"
    state: present
    gid: 8675309
  become: true

- name: add ansible user to media group
  user:
    name: "{{ ansible_user }}"
    groups: "media"
    append: true
  become: true
 
- name: configure jackett basepath
  replace:
    path: "{{ app_folder }}/jackett/ServerConfig.json"
    regexp: '"BasePathOverride": ".*",'
    replace: '"BasePathOverride": "/jackett",'

- name: configure radarr basepath
  replace:
    path: "{{ app_folder }}/radarr/config.xml"
    regexp: '<UrlBase>.*</UrlBase>'
    replace: '<UrlBase>radarr</UrlBase>'

- name: configure sonarr basepath
  replace:
    path: "{{ app_folder }}/sonarr/config.xml"
    regexp: '<UrlBase>.*</UrlBase>'
    replace: '<UrlBase>sonarr</UrlBase>'

- name: configure tautulli basepath
  replace:
    path: "{{ app_folder }}/tautulli/config.ini"
    regexp: 'http_root = ".*"'
    replace: 'http_root = tautulli'

- name: configure tautulli proxy
  replace:
    path: "{{ app_folder }}/tautulli/config.ini"
    regexp: 'http_proxy = 0'
    replace: 'http_proxy = 1'

- name: disable transmission whitelist
  replace:
    path: "{{ app_folder }}/transmission/settings.json"
    regexp: '"rpc-host-whitelist-enabled": true,'
    replace: '"rpc-host-whitelist-enabled": false,'
  ignore_errors: true
