---
- hosts: app_server
  roles:
    - base
    - cockpit
    - caddy

- hosts: media_server
  roles:
    - base
    - cockpit
    - caddy
    - pihole
    - media-server

- hosts:
    - app_server
    - media_server
  tasks:
    - name: update all remaining packages
      apt:
        upgrade: dist
        force: true
      become: true
    - name: clean apt
      apt:
        autoremove: yes
        purge: yes
      become: true
